export const ENV = {
  SERVER_PORT_KEY: 'SERVER_PORT',
  PROTOCOL_KEY: 'PROTOCOL',
  HOST_KEY: 'HOST',
  DB_HOST_KEY: 'DB_HOST',
  DB_PORT_KEY: 'DB_PORT',
  DB_USER_KEY: 'DB_USER',
  DB_PASS_KEY: 'DB_PASS',
  DB_NAME_KEY: 'DB_NAME',
  CA_CERT_KEY: 'CA_CERT',
  JWT_SECRET_KEY: 'JWT_SECRET',
  SALT_ROUNDS_KEY: 'SALT_ROUNDS',
  NODE_ENV_KEY: 'NODE_ENV',
};
