export const ENV = {
  DEV_PROTOCOL_KEYS: 'DEV_PROTOCOL',
  DEV_HOST_KEYS: 'DEV_HOST',
  DB_HOST_KEYS: 'DB_HOST',
  DB_PORT_KEYS: 'DB_PORT',
  DB_USER_KEYS: 'DB_USER',
  DB_PASS_KEYS: 'DB_PASS',
  DB_NAME_KEYS: 'DB_NAME',
  CA_CERT_KEYS: 'CA_CERT',
  JWT_SECRET_KEYS: 'JWT_SECRET',
  SALT_ROUNDS_KEYS: 'SALT_ROUNDS',
};
