name: CD Pipeline

on:
  workflow_run:
    workflows: ['CI Pipeline']
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Pull Docker image
        run: sudo docker pull hyezoprk/apuu-nest:latest

      - name: Clean up Old docker container
        run: sudo docker rm -f apuu-nest-container || true

      - name: Run Docker Container
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
          PROTOCOL: ${{ secrets.PROTOCOL }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SALT_ROUNDS: ${{ secrets.SALT_ROUNDS }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_PASS: ${{ secrets.REDIS_PASS }}
          KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
          KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}
        run: >-
          sudo docker run -d
          -p $PORT:$PORT
          -e PORT=$PORT
          -e DB_HOST=$DB_HOST
          -e DB_PORT=$DB_PORT
          -e DB_USER=$DB_USER
          -e DB_PASS=$DB_PASS
          -e DB_NAME=$DB_NAME
          -e PROTOCOL=$PROTOCOL
          -e HOST=$HOST
          -e JWT_SECRET=$JWT_SECRET
          -e SALT_ROUNDS=$SALT_ROUNDS
          -e EMAIL_USER="$EMAIL_USER"
          -e EMAIL_PASS="$EMAIL_PASS"
          -e REDIS_HOST="$REDIS_HOST"
          -e REDIS_PORT="$REDIS_PORT"
          -e REDIS_PASS="$REDIS_PASS"
          -e KAKAO_CLIENT_ID="$KAKAO_CLIENT_ID"
          -e KAKAO_CLIENT_SECRET="$KAKAO_CLIENT_SECRET"
          -v apuu-nest-public:/usr/src/app/public
          --name apuu-nest-container hyezoprk/apuu-nest
          --network server

      - name: Check Network Connection
        run: sudo docker network connect server apuu-nest-container || true

      - name: Clean up Old docker images
        run: sudo docker image prune -af || true
